#!/bin/sh

# echo -e "Usage:\n docker run -v repoDir:/repo -v htmlDir:/html 99ft/hexo"

cd /repo && git submodule init && git submodule update && npm install
hexo g
rm -rf /html/*
mv /repo/public/* /html
rm -rf /repo/public
exit 0
